# Generated by Django 6.1 on 2026-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='PKR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('support_email', models.EmailField(default='support@apexmarket.com', max_length=254)),
                ('support_phone', models.CharField(default='+92 300 1234567', max_length=20)),
                ('staff_roles_enabled', models.BooleanField(default=True, help_text='Enable different access levels for staff (e.g. Catalog Editor vs Superuser)')),
                ('email_webhooks_enabled', models.BooleanField(default=True, help_text='Send automated email receipts via webhooks')),
                ('auto_maintenance', models.BooleanField(default=False, help_text='Automatically run database maintenance scripts weekly')),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
